server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_APIKEY}
#      model-name: gemini-2.0-flash
  community:
    dashscope:
      chat-model:
        api-key: ${QWEN_APIKEY}
        model-name: qwen-max-latest
#      embedding-model:
#        api-key: ${QWEN_APIKEY}
#        model-name: text-embedding-v3
  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      model-name: llama3.1
    embedding-model:
      base-url: http://localhost:11434
#      model-name: all-minilm
      model-name: nomic-embed-text
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: llama3.1

